WIDTH = 256
HEIGHT = 240
BLOCK_SIZE = 16
TILE_SIZE = 8
NUM_BLOCKS_X = WIDTH / BLOCK_SIZE
NUM_BLOCKS_Y = HEIGHT / BLOCK_SIZE

ARTIFACT_CID = 0
ARTIFACT_DID = 1
ARTIFACT_BCID = 2
ARTIFACT_PID = 2
ARTIFACT_NT = 3

NUM_ALLOWED_PALETTES = 4
PALETTE_SIZE = 4
