WIDTH = 256
HEIGHT = 240
BLOCK_SIZE = 16
TILE_SIZE = 8
NUM_BLOCKS_X = WIDTH // BLOCK_SIZE
NUM_BLOCKS_Y = HEIGHT // BLOCK_SIZE

NUM_TILES_X = NUM_BLOCKS_X * 2
NUM_TILES_Y = NUM_BLOCKS_Y * 2

ARTIFACT_CID = 0
ARTIFACT_DID = 1
ARTIFACT_BCID = 2
ARTIFACT_VCID = 2

NUM_ALLOWED_PALETTES = 4
PALETTE_SIZE = 4
TILE_REUSE_LIMIT = 10

NULL = 0xff
